### ISSUE TITLE
Naming convention for WLCSP

### ISSUE THREAD

**Issue by hvraven** [KiCad/Housings_CSP.pretty#8]
I am currently working on an update for all the STM32 chips by modifying the autogen script located in the library-utils. Currently I am working on automatic assignment of the correct footprint name as the previous version only uses LQFP100, etc.
There I am currently wondering about the packaging information for the WLCSP packages. Most other packages are easy and follow WxHxPitch, but the WLCSP are only labeld by their die number and their pitch. An example can be found [here](http://www.st.com/content/st_com/en/products/microcontrollers/stm32-32-bit-arm-cortex-mcus/stm32-mainstream-mcus/stm32f0-series/stm32f0x1/stm32f031e6.html) on the bottom of the page.

Should I try to convert them to WxH or use the "official" naming scheme instead? And if I should convert them: Is there a generic way for rounding the sizes? They are usually precise on three digits which appears to be a bit excessive.

**Comment by hvraven** [comment]
I now have a script successfully reading most of the sizes from the datasheets. This is the resulting list of footprints, with their occurrence count. By the looks of it they appear to be unique this way, but I am wondering whether thats a sensible way of naming these chips. As far as I understand CSP it is pretty specific and dependent on manufacturer and produced die. Maybe something more specific would make more sense. Any opinions on that?

      1 Housings_CSP:EWLCSP-66_3.639x3.871mm_Pitch0.40mm
      5 Housings_CSP:WLCSP-100_4.166x4.628mm_Pitch0.40mm
      1 Housings_CSP:WLCSP-100_4.775x5.041mm_Pitch0.40mm
      6 Housings_CSP:WLCSP-143_4.521x5.547mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-143_4.539x5.849mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-168_4.891x5.692mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-180_5.5x6mm_Pitch0.65mm
      2 Housings_CSP:WLCSP-25_2.097x2.493mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-25_2.133x2.07mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-25_2.423x2.325mm_Pitch0.40mm
      1 Housings_CSP:WLCSP-36_2.553x2.579mm_Pitch0.40mm
      4 Housings_CSP:WLCSP-36_2.605x2.703mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-36_2.61x2.88mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-49_2.965x2.965mm_Pitch0.40mm
      1 Housings_CSP:WLCSP-49_2.999x3.185mm_Pitch0.40mm
      1 Housings_CSP:WLCSP-49_3.06x3.06mm_Pitch0.40mm
      4 Housings_CSP:WLCSP-49_3.141x3.127mm_Pitch0.40mm
      3 Housings_CSP:WLCSP-49_3.277x3.109mm_Pitch0.40mm
      3 Housings_CSP:WLCSP-49_3.294x3.258mm_Pitch0.40mm
      5 Housings_CSP:WLCSP-49_3.417x3.151mm_Pitch0.40mm
      3 Housings_CSP:WLCSP-64_3.141x3.127mm_Pitch0.35mm
      2 Housings_CSP:WLCSP-64_3.347x3.585mm_Pitch0.40mm
      3 Housings_CSP:WLCSP-64_3.357x3.657mm_Pitch0.40mm
      1 Housings_CSP:WLCSP-64_3.658x3.686mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-64_4.4757x4.4049mm_Pitch0.50mm
      1 Housings_CSP:WLCSP-66_3.639x3.871mm_Pitch0.40mm
      1 Housings_CSP:WLCSP-66_3.767x4.229mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-72_4.4084x3.7594mm_Pitch0.40mm
      1 Housings_CSP:WLCSP-81_3.693x3.815mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-81_4.039x3.951mm_Pitch0.50mm
      1 Housings_CSP:WLCSP-81_4.4084x3.7594mm_Pitch0.40mm
      2 Housings_CSP:WLCSP-90_4.223x3.969mm_Pitch0.40mm

**Comment by SchrodingersGat** [comment]
Sorry for the delay getting back to you, I have been away on vacation.

It appears that even within a single manufacturer (ST in this case) there are multiple options for the same pin count. e.g. WLCSP-**64**_ has many different package sizes.

 I would be in favour of prefixing the manufacturer name (i.e. `ST_`) as these packages are a lot less generic than e.g. `SOIC` parts. 

@jkriege2 @poeschlr what do you guys think?

**Comment by hvraven** [comment]
No worries, vacations are more important.
If one does already prefix the chip with the manufacturer I think it would make sense to use the naming scheme of the manufacturer. For example the [STM32F031E6](http://www.st.com/content/st_com/en/products/microcontrollers/stm32-32-bit-arm-cortex-mcus/stm32-mainstream-mcus/stm32f0-series/stm32f0x1/stm32f031e6.html) uses the `WLCSP-25_2.423x2.325mm_Pitch0.40mm`. ST calls this package `WLCSP 25L P 0.4 MM DIE 444`, so instead of the size they use the die number. As the package itself is built around the die it makes sense as a name.
In KiCad terms that might be `ST_WLCSP-25_Die444_Pitch0.4mm` (or similar). What do you think of this naming scheme for this specific type of packaging? It would be different for every manufacturer, but that is mainly due to the nature of this packaging.

**Comment by SchrodingersGat** [comment]
In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)
